### PR TITLE
Fix minor ESLint problems and add a bit of doc

### LINKED ISSUE #207: Non-blocker, bug: Fix "import and export may only appear at the top level"
This is a non-blocking problem that has to do with ESLint. 

To reproduce the issue:
- Open index.js file
- Open reportWebVital.js file 

You should now see three instances of the above problem in the "problem" tab of VSCode.

### PR DESCRIPTION
**Pull request by jpabadir**
close #207

### CODE REVIEW

File: src/front-end/src/App.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ function App() {
   return (
     <div className="App">
       <Button type="primary" onClick={callServer}>
-        ⏎········Call·the·server!⏎······!
```
Comment (katmartel) [inline src/front-end/src/App.js:16]: I have no idea why ESLint initially told me to format the text like that!! Thank you for fixing it, the way it was before looked so bad

File: documentation/tech-directives/conventions.md [hunk 2]
```diff
@@ -1,26 +1,10 @@
...
-// Like so: getDouble();<br>
-// Not like so: doubled();<br>
-- Use tabs, not spaces.<br>
-- Put a space after a word:<br>
-// Incorrect: if(true){<br>
-// Correct: if (true) {
+## Back-end
+We use the [JavaScript Standard Style Guide](https://standardjs.com/), which is enforced by ESLint in continuous integration. 
 
 ## File naming
```
Comment (katmartel) [inline documentation/tech-directives/conventions.md:9]: It might be worth it to also add the naming convention for branches when it comes to working on issues, just so that we have it documented.

**Review by katmartel — APPROVED** [review]
Looks good, thanks for updating documentation and for looking into the ESLint problem!

**Review by wrc9817 — APPROVED** [review]

**Review by aleksssk — APPROVED** [review]
Nice work

File: src/front-end/src/App.js (hunk 1 above)
Comment (jpabadir) [reply src/front-end/src/App.js:16]: Haha yeah no worries, I don't know either =)

File: documentation/tech-directives/conventions.md (hunk 2 above)
Comment (jpabadir) [reply documentation/tech-directives/conventions.md:9]: Added, thanks for the suggestion!
