### PR TITLE
393 resend verification email + minor bug fixes

### LINKED ISSUE #393: Enable resending of verifying email to user
Right now, if I sign up and don't verify my email fast enough, I am stuck and cannot use my account nor delete it.

### PR DESCRIPTION
**Pull request by katmartel**

### CODE REVIEW

File: src/front-end/src/helper-methods.js [hunk 1]
```diff
@@ -2,6 +2,29 @@ import firebase from './firebase-init';
...
+            'Please check the inbox and junk folder of your email before pressing the button again',
+          );
+          break;
+        default:
+          break;
+      }
+    });
+}
+
 function mySendEmailVerification(user) {
```
Comment (katmartel) [inline src/front-end/src/helper-methods.js]: Please note: I'm aware that the resendVerificationEmail function is essentially the same as the mySendEmailVerification function. I did try to export mySendEmailVerification instead, however, the window alerts weren't being displayed correctly (despite my best efforts, such as using try catch statements). As such, I made the resendVerificationEmail function since the mySendEmailVerification is used to send the verification to admins and mentors upon signup (and thus do not need the popups like the resendVerificationEmail function does)

File: src/front-end/src/components/AccountMenuItem/AccountMenuItem.js [hunk 2]
```diff
@@ -17,7 +17,12 @@ function AccountMenuItem() {
   });
 
   const onLogout = () => {
-    fire.auth().signOut();
+    fire
+      .auth()
+      .signOut()
+      .then(() => {
+        window.location.href = '/my-account';
+      });
```
Comment (katmartel) [inline src/front-end/src/components/AccountMenuItem/AccountMenuItem.js:25]: To fix the bug of being left on the same page after logging out:

File: src/front-end/src/components/ForgotPassword/ForgotPassword.js [hunk 3]
```diff
@@ -15,7 +15,6 @@ class ForgotPassword extends Component {
   localResetPassword() {
     // TODO: implement some validation here
     resetPassword(this.state.email);
-    window.alert('We sent you an email with a link to reset your password.');
```
Comment (katmartel) [inline src/front-end/src/components/ForgotPassword/ForgotPassword.js:18]: Removed this because it would be displayed if an email wasn't entered, but it should only be displayed if a proper email was in the input (see also the updated mySendEmailVerification(user) function in helper-methods)

File: src/front-end/src/components/Login.js [hunk 4]
```diff
@@ -124,7 +124,7 @@ class Login extends Component {
             <p>
               <a
                 className="loginlink"
-                href="http://localhost:3000/ForgotPassword
+                href="http://localhost:3000/forgot-password
```
Comment (katmartel) [inline src/front-end/src/components/Login.js:127]: To fix the issue of not being redirected to the correct page when the 'Forgot your password?' link is clicked:

**Review by aleksssk — APPROVED** [review]
Nice work, I will merge the pr today :) !

File: src/front-end/src/components/AccountMenuItem/AccountMenuItem.js (hunk 2 above)
Comment (jpabadir) [reply src/front-end/src/components/AccountMenuItem/AccountMenuItem.js:25]: Nice! That was annoying me :)

File: src/front-end/src/helper-methods.js [hunk 5]
```diff
@@ -2,6 +2,27 @@ import firebase from './firebase-init';
 
 const auth = firebase.auth();
 
+export function resendVerificationEmail(user) {
+  user
+    .sendEmailVerification()
+    .then(() => {
+      window.alert('A new verification email has successfully been sent!');
+      console.log('Success');
```
Comment (jpabadir) [inline src/front-end/src/helper-methods.js]: I'd remove the console.log here, since we are already doing a window.alert.

File: src/front-end/src/helper-methods.js [hunk 6]
```diff
@@ -2,6 +2,27 @@ import firebase from './firebase-init';
...
+    .catch((error) => {
+      console.log(error);
+      switch (error.code) {
+        case 'auth/too-many-requests':
+          window.alert(
+            'Please check the inbox and junk folder of your email before pressing the button again',
+          );
+          break;
+        default:
+          break;
```
Comment (jpabadir) [inline src/front-end/src/helper-methods.js]: Did you use a switch instead of an if here in case in the future we want to add more error code handling? If not, I'd use a simple if statement here since this switch only has one case.

File: src/front-end/src/helper-methods.js [hunk 7]
```diff
@@ -2,6 +2,27 @@ import firebase from './firebase-init';
...
+    .then(() => {
+      window.alert('A new verification email has successfully been sent!');
+      console.log('Success');
+    })
+    .catch((error) => {
+      console.log(error);
+      switch (error.code) {
+        case 'auth/too-many-requests':
+          window.alert(
+            'Please check the inbox and junk folder of your email before pressing the button again',
```
Comment (jpabadir) [inline src/front-end/src/helper-methods.js]: I'd change this to "Too many requests. Please check the inbox and junk folder of your email before pressing the button again." just so the user understands why we're saying that.

File: src/front-end/src/helper-methods.js [hunk 8]
```diff
@@ -68,10 +89,17 @@ export function resetPassword(emailAddress) {
...
       console.log('Email sent');
     })
     .catch((error) => {
       console.log(error);
+      switch (error.code) {
+        case 'auth/invalid-email':
+          break;
+        default:
+          break;
+      }
```
Comment (jpabadir) [inline src/front-end/src/helper-methods.js]: This code doesn't do anything. If you meant to print the error, you can update it. Otherwise, you can delete the whole switch statement.

File: src/front-end/src/helper-methods.js [hunk 9]
```diff
@@ -68,10 +89,17 @@ export function resetPassword(emailAddress) {
   auth
     .sendPasswordResetEmail(emailAddress)
     .then(() => {
+      window.alert('We sent you an email with a link to reset your password.');
       console.log('Email sent');
```
Comment (jpabadir) [inline src/front-end/src/helper-methods.js]: I think we can remove my console.log here since now we have a window.alert.

File: src/front-end/src/helper-methods.js [hunk 10]
```diff
@@ -2,6 +2,27 @@ import firebase from './firebase-init';
 
 const auth = firebase.auth();
 
+export function resendVerificationEmail(user) {
```
Comment (jpabadir) [inline src/front-end/src/helper-methods.js:5]: Why make a new method instead of reusing `mySendEmailVerification` and adapting it as needed?

**Review by jpabadir — APPROVED** [review]

File: src/front-end/src/helper-methods.js (hunk 6 above)
Comment (katmartel) [reply src/front-end/src/helper-methods.js]: Yea I made a switch just incase we come across other errors in the future so it's easier to address!

File: src/front-end/src/helper-methods.js (hunk 8 above)
Comment (katmartel) [reply src/front-end/src/helper-methods.js]: Before I added this in, if a user hit the 'Confirm' button even without adding any input, the 'We sent you an email with a link to reset your password' popup would be displayed. I added the switch statement to catch that, so that the red input error will be displayed (so the break does as I intended). I'll also add in the case for when an email address is entered which isn't in our DB (auth/user-not-found)

Comment (jpabadir) [reply src/front-end/src/helper-methods.js]: My mistake then, I was wrong! Sorry!
